sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - node_modules
before_script:
   - wget -qO- https://toolbelt.heroku.com/install.sh | sh
script:
  - mvn clean install
before_install:
  - docker pull openjdk:9
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
