sudo: required
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - .autoconf
    - ~/.m2
    - node_modules
before_script:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
script:
  - ./build_and_push.sh
before_install:
  - docker pull openjdk:9
  - sudo apt-get install curl && curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install nodejs