sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - .autoconf
    - ~/.m2
    - node_modules
before_script:
   - wget -qO- https://toolbelt.heroku.com/install.sh | sh
script:
  - mvn clean install
  - docker_push.sh
before_install:
  - docker pull openjdk:9
